# Generated by Django 3.1 on 2021-04-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avalanche_Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avalanche_Number', models.IntegerField()),
                ('Name', models.CharField(max_length=500)),
                ('Lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
