# Generated by Django 3.2 on 2021-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Lat',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Long',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
