# Generated by Django 3.2 on 2021-05-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0003_auto_20210424_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalanche_accident',
            name='Lat',
            field=models.DecimalField(decimal_places=5, default=9999, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='Long',
            field=models.DecimalField(decimal_places=5, default=9999, max_digits=12),
            preserve_default=False,
        ),
    ]
