# Generated by Django 3.2 on 2021-05-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0004_auto_20210507_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Date',
            field=models.CharField(default='INPUT DATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Lat',
            field=models.DecimalField(decimal_places=10, default=9999, max_digits=50),
        ),
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Long',
            field=models.DecimalField(decimal_places=10, default=9999, max_digits=50),
        ),
        migrations.AlterField(
            model_name='avalanche_accident',
            name='Name',
            field=models.CharField(default='INPUT NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='avalanche_accident',
            name='State',
            field=models.CharField(default='INPUT STATE', max_length=100),
        ),
    ]
