# Generated by Django 3.2.3 on 2021-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0005_auto_20210510_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avalanche_accident',
            old_name='Avalanche_Number',
            new_name='avalanche_number',
        ),
        migrations.RenameField(
            model_name='avalanche_accident',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='avalanche_accident',
            old_name='Name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='avalanche_accident',
            old_name='State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='avalanche_accident',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='avalanche_accident',
            name='Long',
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='killed',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=9999, max_digits=50),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='location_setting',
            field=models.CharField(default='INPUT NAME', max_length=1000),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=9999, max_digits=50),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='primary_activity',
            field=models.CharField(default='INPUT NAME', max_length=1000),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='primary_travel_mode',
            field=models.CharField(default='INPUT NAME', max_length=1000),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='summary_description',
            field=models.CharField(default='INPUT SUMMARY DESCRIPTION', max_length=1000),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='type',
            field=models.CharField(default='INPUT NAME', max_length=1000),
        ),
        migrations.AddField(
            model_name='avalanche_accident',
            name='url',
            field=models.CharField(default='INPUT URL', max_length=1000),
        ),
    ]
