# Generated by Django 3.2.3 on 2021-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0007_remove_avalanche_accident_avalanche_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalanche_accident',
            name='avalanche_number',
            field=models.IntegerField(default=9999),
        ),
    ]
