# Generated by Django 3.2.3 on 2021-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0008_avalanche_accident_avalanche_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalanche_accident',
            name='html',
            field=models.CharField(default='INPUT HTML', max_length=100000),
        ),
    ]
