# Generated by Django 3.2.3 on 2021-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_data', '0009_avalanche_accident_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalanche_accident',
            name='audio_url',
            field=models.CharField(default='INPUT AUDIO URL', max_length=2000),
        ),
    ]
